[package]
name = "migration"
version = "0.1.2"
edition = "2021"
authors = ["MXWXZ <matrixwxz@gmail.com>"]
publish = false

[dependencies]
sea-orm-migration = { version = "1.1", features = [
    "sqlx-sqlite",
    "sqlx-postgres",
    "sqlx-mysql",
    "runtime-tokio-rustls",
] }
